### ISSUE TITLE
ERR_MODULE_NOT_FOUND with version 1.8.0

### ISSUE THREAD

**Issue by kevin-belellou** [GaelGirodon/ci-badges-action#11]
Hello,

I encounter an error in my pipeline with the new release 1.8.0 (this pipeline was working fine with last release v1.7.0):

> Run gaelgirodon/ci-badges-action@5541894eeec0eecf8079d434ff3c5f3a8669c559
> node:internal/modules/esm/resolve:873
>   throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
>         ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@actions/core' imported from /home/runner/work/_actions/gaelgirodon/ci-badges-action/5541894eeec0eecf8079d434ff3c5f3a8669c559/src/index.js
>     at packageResolve (node:internal/modules/esm/resolve:873:9)
>     at moduleResolve (node:internal/modules/esm/resolve:946:18)
>     at defaultResolve (node:internal/modules/esm/resolve:1188:11)
>     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:642:12)
>     at #cachedDefaultResolve (node:internal/modules/esm/loader:591:25)
>     at ModuleLoader.resolve (node:internal/modules/esm/loader:574:38)
>     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:236:38)
>     at ModuleJob._link (node:internal/modules/esm/module_job:130:49) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> 
> Node.js v20.19.0

My pipeline looks like this:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: "Update CI badges"
        uses: gaelgirodon/ci-badges-action@d4394e8ae1180779c579e768aea23a0e7b02c53a
        env:
          GIST_ID: ${{ github.event_name == 'push' && github.ref_name == 'main' && env.CI_BADGES_GIST || env.CI_BADGES_GIST_STAGING }}
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.CI_BADGES_GIST_TOKEN }}
```

Thank you for your action and for your time
