### ISSUE TITLE
Could you publish new version with the LCOV support?

### ISSUE THREAD

**Issue by gadicc** [GaelGirodon/ci-badges-action#3]
Hey there.  Great package, thanks.  The LCOV support seems to work great, could you publish a new version that includes it?

For everyone else, you can do this in the meantime:

```yaml
      - name: Prepare packages for next step (remove after non-sha release)
        run: cd /home/runner/work/_actions/gaelgirodon/ci-badges-action && npm i -D @actions/core @actions/github @actions/glob

      - name: Upload coverage to gist
        uses: gaelgirodon/ci-badges-action@4059134f9f9e113d77dd4f05a47db8b62c09848c
```
