### ISSUE TITLE
GitHub workflow fails with v1.7.0

### ISSUE THREAD

**Issue by kevin-belellou** [GaelGirodon/ci-badges-action#7]
Updating this action to v1.7.0 results in this exception

```
Run gaelgirodon/ci-badges-action@4a88710bf82fb2882382f235c140c1cd94e3d546
node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@actions/core' imported from /home/runner/work/_actions/gaelgirodon/ci-badges-action/4a88710bf82fb2882382f235c140c1cd94e3d546/src/index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:[18](https://github.com/kevin-belellou/advent-of-code/actions/runs/12127174655/job/33840500245#step:8:19))
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.18.0
```

GitHub workflow code as under and is working in v1.6.0 
```
- name: "Update CI badges"
        uses: gaelgirodon/ci-badges-action@4a88710bf82fb2882382f235c140c1cd94e3d546
        env:
          GIST_ID: ${{ github.event_name == 'push' && github.ref_name == 'main' && env.CI_BADGES_GIST || env.CI_BADGES_GIST_STAGING }}
        with:
          gist-id: ${{ env.GIST_ID }}
          token: ${{ secrets.CI_BADGES_GIST_TOKEN }}
```

Workflow running on ubuntu-latest (22.04.5), runner version 2.321.0
